import { Inter } from "next/font/google";
import {
  ClerkProvider,
  RedirectToSignIn,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
        <SignedOut>
              <RedirectToSignIn />
            </SignedOut>
            <SignedIn>
              <Header />
              {children}
            </SignedIn>
          </body>
        </html>
    </ClerkProvider>
  );
}

// Header component without the toggle button
function Header() {

  return (
    <header
      style={{
        display: "flex",
        justifyContent: "flex-end",
        padding: "1rem",
      }}
    >
      <UserButton />
    </header>
  );
}
